services:
  - type: web
    name: django-app
    env: docker
    plan: free
    # branch: master  # 👈 Important!
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: project.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: 'False'
