services:
  - type: web
    name: django-app
    env: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /
    dockerContext: .
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: project.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: 'False'
